name: Main

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]
    
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install
        run: npm install
          
      - name: Lint
        run: npm run lint

      - name: Test:Unit
        run: npm run test:ci

      - name: Test:E2E
        uses: cypress-io/github-action@v4
        with:
          command: npm run cy:ci
          browser: chrome

      - name: Upload screenshots (On Failure)
        uses: actions/upload-artifact@v3
        if: failure()
        with:
            name: cypress-snapshots
            path: |
              cypress/screenshots
              cypress/**/__image_snapshots__/*.actual.png
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
